---
- name: (PHPMYADMIN) Installing dbconfig-common
  package:
    name: dbconfig-common
    state: latest

- name: (PHPMYADMIN) Pre-configure database
  template:
    src: dbconfig-common.conf
    dest: /etc/dbconfig-common/phpmyadmin.conf
    owner: root
    group: root
    mode: 0600

- name: (PHPMYADMIN) Installing phpmyadmin
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - phpmyadmin
    - dnsutils
